GET http://localhost:1234/tasks
###

GET http://localhost:1234/tasks/012-345

###
POST http://localhost:1234/tasks
content-type: application/json

{
    "title": "Hacer la tarea de técnica",
    "description": "Hacer la tarea de calidad",
    "priority": "Baja",
    "status": "Pendiente"
}

###

DELETE http://localhost:1234/tasks/8eab6ecc-f7a0-4b14-b34b-ab402988947c

###

PATCH  http://localhost:1234/tasks/012-345
content-type: application/json

{
    "status": "Pendiente"
}